"""cayleypy-rapapport-m2 baseline solver

Kaggle competition: https://www.kaggle.com/competitions/cayleypy-rapapport-m2

This file implements a *constructive* sorting algorithm using only the
allowed generators (moves) from the competition definition:

- S : swap positions 0 and 1
- I : swap (0,1), (2,3), (4,5), ...
- K : swap (1,2), (3,4), (5,6), ...

The goal is to transform an arbitrary permutation into the sorted state.

We use a simple (not optimal) O(n^3) algorithm:
- Consider the permutation C generated by the pair (I, K).
  Along the index order
      [0, 2, 4, ..., largest even, largest odd, ..., 3, 1]
  adjacent swaps can be realized by conjugation of S.
- Using powers of that cycle, we realize adjacent transpositions in the cycle
  order and insertion-sort the array relative to the globally sorted target.

The produced move sequence is valid for the competition, but not score-optimal.

The module exposes:
    solve(vec) -> (moves, sorted_array)

and can be executed as a script:
    python solve_module.py "[3,0,1,4,2]"

It prints JSON: {"moves": [...], "sorted_array": [...]}
"""

from __future__ import annotations

import json
import sys
from typing import List, Sequence, Tuple

Move = str


def _apply_S(a: List[int]) -> None:
    if len(a) >= 2:
        a[0], a[1] = a[1], a[0]


def _apply_I(a: List[int]) -> None:
    n = len(a)
    i = 0
    while i + 1 < n:
        a[i], a[i + 1] = a[i + 1], a[i]
        i += 2


def _apply_K(a: List[int]) -> None:
    n = len(a)
    i = 1
    while i + 1 < n:
        a[i], a[i + 1] = a[i + 1], a[i]
        i += 2


def _apply_move(a: List[int], m: Move) -> None:
    if m == "S":
        _apply_S(a)
    elif m == "I":
        _apply_I(a)
    elif m == "K":
        _apply_K(a)
    else:
        raise ValueError(f"Unknown move: {m!r}")


def _cycle_order(n: int) -> List[int]:
    evens = list(range(0, n, 2))
    last_odd = n - 1 if (n - 1) % 2 == 1 else n - 2
    odds_desc = list(range(last_odd, 0, -2))
    return evens + odds_desc


def _swap_adjacent_in_cycle(n: int, j: int) -> List[Move]:
    if j <= 0 or j >= n:
        raise ValueError("j must satisfy 1 <= j < n")
    forward = n - j
    backward = j
    seq: List[Move] = []
    if backward <= forward:
        for _ in range(backward):
            seq.append("K")
            seq.append("I")
    else:
        for _ in range(forward):
            seq.append("I")
            seq.append("K")
    return seq + ["S"] + list(reversed(seq))


def solve(vec: Sequence[int]) -> Tuple[List[Move], List[int]]:
    a = list(vec)
    n = len(a)
    if n <= 1:
        return [], a
    target = sorted(a)
    cycle = _cycle_order(n)
    inv_cycle = [0] * n
    for pos_in_cycle, idx in enumerate(cycle):
        inv_cycle[idx] = pos_in_cycle
    moves: List[Move] = []
    for j in range(n):
        dest_idx = cycle[j]
        desired_val = target[dest_idx]
        cur_idx = 0
        while cur_idx < n and a[cur_idx] != desired_val:
            cur_idx += 1
        if cur_idx >= n:
            raise RuntimeError("desired value not found (input not a permutation?)")
        cur_pos = inv_cycle[cur_idx]
        while cur_pos > j:
            seq = _swap_adjacent_in_cycle(n, cur_pos)
            for m in seq:
                _apply_move(a, m)
            moves.extend(seq)
            cur_pos -= 1
    return moves, a


def _main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python solve_module.py '[3,0,1,4,2]'", file=sys.stderr)
        raise SystemExit(2)
    vec = json.loads(sys.argv[1])
    if not isinstance(vec, list):
        raise SystemExit("Input must be a JSON list")
    moves, sorted_array = solve(vec)
    print(json.dumps({"moves": moves, "sorted_array": sorted_array}))


if __name__ == "__main__":
    _main()
